import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';

import { FLAGS, renderFlag } from './flags';
import {
  EQUIPMENT_ICONS, PORTRAIT_ICONS, RESOURCE_ICONS, UI_ICONS, UNIT_ICONS,
} from './icons';

/**
 * Writes the generated asset set and a manifest describing it.
 *
 * The manifest is what the load-time test asserts against: total size, per-file
 * size, and the expected inventory. An asset budget that is not measured is not
 * a budget.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const OUT = join(ROOT, 'public', 'assets');

interface AssetEntry {
  path: string;
  bytes: number;
  gzipBytes: number;
}

async function writeAsset(
  rel: string, contents: string, entries: AssetEntry[],
): Promise<void> {
  const full = join(OUT, rel);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, contents, 'utf8');
  entries.push({
    path: `assets/${rel}`,
    bytes: Buffer.byteLength(contents, 'utf8'),
    gzipBytes: gzipSync(Buffer.from(contents, 'utf8')).length,
  });
}

/**
 * Copies the fetched officer photographs in, and reports whose we have.
 *
 * The set is written out as a generated module rather than discovered at
 * runtime, because the alternative is asking for a file that is not there and
 * reading the 404 -- and a 404 is a thing the asset test counts.
 */
async function copyPortraits(entries: AssetEntry[]): Promise<string[]> {
  const from = join(__dirname, 'portraits');
  let names: string[];
  try {
    names = (await readdir(from)).filter((n) => n.endsWith('.webp'));
  } catch {
    return [];
  }
  const ids: string[] = [];
  for (const name of names.sort()) {
    const buf = await readFile(join(from, name));
    const rel = `portraits/${name}`;
    const full = join(OUT, rel);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, buf);
    entries.push({
      path: `assets/${rel}`,
      bytes: buf.byteLength,
      // Already compressed; gzip only makes it bigger, so the honest figure
      // for the transfer budget is the file itself.
      gzipBytes: buf.byteLength,
    });
    ids.push(name.replace(/\.webp$/, ''));
  }
  return ids;
}

async function main(): Promise<void> {
  await rm(OUT, { recursive: true, force: true });
  const entries: AssetEntry[] = [];

  for (const [tag, spec] of Object.entries(FLAGS)) {
    await writeAsset(`flags/${tag}.svg`, renderFlag(spec), entries);
  }
  for (const [name, body] of Object.entries(RESOURCE_ICONS)) {
    await writeAsset(`icons/resource-${name}.svg`, body, entries);
  }
  for (const [name, body] of Object.entries(UI_ICONS)) {
    await writeAsset(`icons/ui-${name}.svg`, body, entries);
  }
  for (const [name, body] of Object.entries(EQUIPMENT_ICONS)) {
    await writeAsset(`icons/equipment-${name}.svg`, body, entries);
  }
  for (const [name, body] of Object.entries(UNIT_ICONS)) {
    await writeAsset(`units/${name}.svg`, body, entries);
  }
  // The drawn silhouettes are the fallback: a commander with no photograph,
  // and every commander at all until the fetcher has been run.
  for (const [name, body] of Object.entries(PORTRAIT_ICONS)) {
    await writeAsset(`portraits/fallback-${name}.svg`, body, entries);
  }
  // The photographs, fetched by `npm run portraits` and committed. Copied
  // rather than generated so the ordinary build stays offline: the network is
  // not something a build should need.
  const photographed = await copyPortraits(entries);

  entries.sort((a, b) => a.path.localeCompare(b.path));
  const totalBytes = entries.reduce((s, e) => s + e.bytes, 0);
  const totalGzip = entries.reduce((s, e) => s + e.gzipBytes, 0);

  const manifest = {
    generated: 'tools/asset-gen/build.ts',
    counts: {
      flags: Object.keys(FLAGS).length,
      resourceIcons: Object.keys(RESOURCE_ICONS).length,
      uiIcons: Object.keys(UI_ICONS).length,
      equipmentIcons: Object.keys(EQUIPMENT_ICONS).length,
      unitIcons: Object.keys(UNIT_ICONS).length,
      portraitFallbacks: Object.keys(PORTRAIT_ICONS).length,
      portraits: photographed.length,
    },
    totalBytes,
    totalGzipBytes: totalGzip,
    assets: entries,
  };
  await writeFile(join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 2));

  // Which commanders have a face, for the interface to ask before it asks for
  // the file.
  const index = join(ROOT, 'src', 'ui', 'portraitIndex.ts');
  await writeFile(index,
    '/* Generated by tools/asset-gen/build.ts. Do not edit. */\n'
    + '/** Commanders with a photograph; everyone else gets a drawn fallback. */\n'
    + 'export const PHOTOGRAPHED: ReadonlySet<string> = new Set([\n'
    + photographed.map((id) => `  '${id}',`).join('\n')
    + '\n]);\n');

  console.log(
    `assets: ${entries.length} files, ${(totalBytes / 1024).toFixed(1)} KB ` +
    `(${(totalGzip / 1024).toFixed(1)} KB gzipped)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
